apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      command: ["sh", "-c", "touch /tmp/ready; sleep 3600" ]  
      readinessProbe: 
       exec: 
         command: 
         - cat 
         - /tmp/ready 
       initialDelaySeconds: 5 
       periodSeconds: 10 
       failureThreshold: 1  
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: busybox 
  namespace: test 
spec: 
  containers:
    - name: busybox 
      image: registry.k8s.io/e2e-test-images/agnhost:2.40
      args:
      - liveness
      livenessProbe: 
        httpGet: 
          path: /heathz 
          port: 8080
          httpsHeaders: 
            - name: Custom-Header 
              value: livenessProbe 
        initialDelaySeconds: 3 
        periodSeconds: 10        



