apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: taints
  labels: 
    app: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: prod
  template:
    metadata:
      labels:
        app: prod
    spec:
      nodeSelector: 
        env: prod
        storage: ssd
      containers:
      - name: myapp1
        image: nginx:latest

