apiVersion: v1
kind: Pod
metadata:
  name: secure-writable
  namespace: test
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        privileged: true
        readOnlyRootFilesystem: true
