apiVersion: v1
kind: Pod
metadata:
  name: capabilites-pod 
  namespace: test
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
          # add:
          #   - NET_ADMIN
          #   - SYS_TIME